/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsAttributes from './DungeonsandtrollsAttributes';
import DungeonsandtrollsDamageType from './DungeonsandtrollsDamageType';

/**
 * The DungeonsandtrollsEffect model module.
 * @module model/DungeonsandtrollsEffect
 * @version 1.7.0
 */
class DungeonsandtrollsEffect {
    /**
     * Constructs a new <code>DungeonsandtrollsEffect</code>.
     * @alias module:model/DungeonsandtrollsEffect
     */
    constructor() { 
        
        DungeonsandtrollsEffect.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsEffect</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsEffect} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsEffect} The populated <code>DungeonsandtrollsEffect</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsEffect();

            if (data.hasOwnProperty('damageAmount')) {
                obj['damageAmount'] = ApiClient.convertToType(data['damageAmount'], 'Number');
            }
            if (data.hasOwnProperty('damageType')) {
                obj['damageType'] = DungeonsandtrollsDamageType.constructFromObject(data['damageType']);
            }
            if (data.hasOwnProperty('effects')) {
                obj['effects'] = DungeonsandtrollsAttributes.constructFromObject(data['effects']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('CasterId')) {
                obj['CasterId'] = ApiClient.convertToType(data['CasterId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} damageAmount
 */
DungeonsandtrollsEffect.prototype['damageAmount'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsDamageType} damageType
 */
DungeonsandtrollsEffect.prototype['damageType'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} effects
 */
DungeonsandtrollsEffect.prototype['effects'] = undefined;

/**
 * @member {Number} duration
 */
DungeonsandtrollsEffect.prototype['duration'] = undefined;

/**
 * @member {String} CasterId
 */
DungeonsandtrollsEffect.prototype['CasterId'] = undefined;






export default DungeonsandtrollsEffect;

