/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsAttributes model module.
 * @module model/DungeonsandtrollsAttributes
 * @version 1.7.0
 */
class DungeonsandtrollsAttributes {
    /**
     * Constructs a new <code>DungeonsandtrollsAttributes</code>.
     * @alias module:model/DungeonsandtrollsAttributes
     */
    constructor() { 
        
        DungeonsandtrollsAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsAttributes} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsAttributes} The populated <code>DungeonsandtrollsAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsAttributes();

            if (data.hasOwnProperty('strength')) {
                obj['strength'] = ApiClient.convertToType(data['strength'], 'Number');
            }
            if (data.hasOwnProperty('dexterity')) {
                obj['dexterity'] = ApiClient.convertToType(data['dexterity'], 'Number');
            }
            if (data.hasOwnProperty('intelligence')) {
                obj['intelligence'] = ApiClient.convertToType(data['intelligence'], 'Number');
            }
            if (data.hasOwnProperty('willpower')) {
                obj['willpower'] = ApiClient.convertToType(data['willpower'], 'Number');
            }
            if (data.hasOwnProperty('constitution')) {
                obj['constitution'] = ApiClient.convertToType(data['constitution'], 'Number');
            }
            if (data.hasOwnProperty('slashResist')) {
                obj['slashResist'] = ApiClient.convertToType(data['slashResist'], 'Number');
            }
            if (data.hasOwnProperty('pierceResist')) {
                obj['pierceResist'] = ApiClient.convertToType(data['pierceResist'], 'Number');
            }
            if (data.hasOwnProperty('fireResist')) {
                obj['fireResist'] = ApiClient.convertToType(data['fireResist'], 'Number');
            }
            if (data.hasOwnProperty('poisonResist')) {
                obj['poisonResist'] = ApiClient.convertToType(data['poisonResist'], 'Number');
            }
            if (data.hasOwnProperty('electricResist')) {
                obj['electricResist'] = ApiClient.convertToType(data['electricResist'], 'Number');
            }
            if (data.hasOwnProperty('life')) {
                obj['life'] = ApiClient.convertToType(data['life'], 'Number');
            }
            if (data.hasOwnProperty('stamina')) {
                obj['stamina'] = ApiClient.convertToType(data['stamina'], 'Number');
            }
            if (data.hasOwnProperty('mana')) {
                obj['mana'] = ApiClient.convertToType(data['mana'], 'Number');
            }
            if (data.hasOwnProperty('constant')) {
                obj['constant'] = ApiClient.convertToType(data['constant'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} strength
 */
DungeonsandtrollsAttributes.prototype['strength'] = undefined;

/**
 * @member {Number} dexterity
 */
DungeonsandtrollsAttributes.prototype['dexterity'] = undefined;

/**
 * @member {Number} intelligence
 */
DungeonsandtrollsAttributes.prototype['intelligence'] = undefined;

/**
 * @member {Number} willpower
 */
DungeonsandtrollsAttributes.prototype['willpower'] = undefined;

/**
 * @member {Number} constitution
 */
DungeonsandtrollsAttributes.prototype['constitution'] = undefined;

/**
 * @member {Number} slashResist
 */
DungeonsandtrollsAttributes.prototype['slashResist'] = undefined;

/**
 * @member {Number} pierceResist
 */
DungeonsandtrollsAttributes.prototype['pierceResist'] = undefined;

/**
 * @member {Number} fireResist
 */
DungeonsandtrollsAttributes.prototype['fireResist'] = undefined;

/**
 * @member {Number} poisonResist
 */
DungeonsandtrollsAttributes.prototype['poisonResist'] = undefined;

/**
 * @member {Number} electricResist
 */
DungeonsandtrollsAttributes.prototype['electricResist'] = undefined;

/**
 * @member {Number} life
 */
DungeonsandtrollsAttributes.prototype['life'] = undefined;

/**
 * @member {Number} stamina
 */
DungeonsandtrollsAttributes.prototype['stamina'] = undefined;

/**
 * @member {Number} mana
 */
DungeonsandtrollsAttributes.prototype['mana'] = undefined;

/**
 * @member {Number} constant
 */
DungeonsandtrollsAttributes.prototype['constant'] = undefined;






export default DungeonsandtrollsAttributes;

