/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsWaypoint model module.
 * @module model/DungeonsandtrollsWaypoint
 * @version 1.7.0
 */
class DungeonsandtrollsWaypoint {
    /**
     * Constructs a new <code>DungeonsandtrollsWaypoint</code>.
     * @alias module:model/DungeonsandtrollsWaypoint
     */
    constructor() { 
        
        DungeonsandtrollsWaypoint.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsWaypoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsWaypoint} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsWaypoint} The populated <code>DungeonsandtrollsWaypoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsWaypoint();

            if (data.hasOwnProperty('destinationFloor')) {
                obj['destinationFloor'] = ApiClient.convertToType(data['destinationFloor'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} destinationFloor
 */
DungeonsandtrollsWaypoint.prototype['destinationFloor'] = undefined;






export default DungeonsandtrollsWaypoint;

