/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsAttributes from './DungeonsandtrollsAttributes';
import DungeonsandtrollsDroppable from './DungeonsandtrollsDroppable';
import DungeonsandtrollsEffect from './DungeonsandtrollsEffect';
import DungeonsandtrollsItem from './DungeonsandtrollsItem';
import DungeonsandtrollsSimpleItem from './DungeonsandtrollsSimpleItem';
import DungeonsandtrollsStun from './DungeonsandtrollsStun';

/**
 * The DungeonsandtrollsMonster model module.
 * @module model/DungeonsandtrollsMonster
 * @version 1.7.0
 */
class DungeonsandtrollsMonster {
    /**
     * Constructs a new <code>DungeonsandtrollsMonster</code>.
     * @alias module:model/DungeonsandtrollsMonster
     */
    constructor() { 
        
        DungeonsandtrollsMonster.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsMonster</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsMonster} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsMonster} The populated <code>DungeonsandtrollsMonster</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsMonster();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [DungeonsandtrollsSimpleItem]);
            }
            if (data.hasOwnProperty('effects')) {
                obj['effects'] = ApiClient.convertToType(data['effects'], [DungeonsandtrollsEffect]);
            }
            if (data.hasOwnProperty('lifePercentage')) {
                obj['lifePercentage'] = ApiClient.convertToType(data['lifePercentage'], 'Number');
            }
            if (data.hasOwnProperty('faction')) {
                obj['faction'] = ApiClient.convertToType(data['faction'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = DungeonsandtrollsAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('equippedItems')) {
                obj['equippedItems'] = ApiClient.convertToType(data['equippedItems'], [DungeonsandtrollsItem]);
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('algorithm')) {
                obj['algorithm'] = ApiClient.convertToType(data['algorithm'], 'String');
            }
            if (data.hasOwnProperty('onDeath')) {
                obj['onDeath'] = ApiClient.convertToType(data['onDeath'], [DungeonsandtrollsDroppable]);
            }
            if (data.hasOwnProperty('maxAttributes')) {
                obj['maxAttributes'] = DungeonsandtrollsAttributes.constructFromObject(data['maxAttributes']);
            }
            if (data.hasOwnProperty('lastDamageTaken')) {
                obj['lastDamageTaken'] = ApiClient.convertToType(data['lastDamageTaken'], 'Number');
            }
            if (data.hasOwnProperty('stun')) {
                obj['stun'] = DungeonsandtrollsStun.constructFromObject(data['stun']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
DungeonsandtrollsMonster.prototype['id'] = undefined;

/**
 * @member {String} name
 */
DungeonsandtrollsMonster.prototype['name'] = undefined;

/**
 * @member {String} icon
 */
DungeonsandtrollsMonster.prototype['icon'] = undefined;

/**
 * @member {Array.<module:model/DungeonsandtrollsSimpleItem>} items
 */
DungeonsandtrollsMonster.prototype['items'] = undefined;

/**
 * @member {Array.<module:model/DungeonsandtrollsEffect>} effects
 */
DungeonsandtrollsMonster.prototype['effects'] = undefined;

/**
 * @member {Number} lifePercentage
 */
DungeonsandtrollsMonster.prototype['lifePercentage'] = undefined;

/**
 * @member {String} faction
 */
DungeonsandtrollsMonster.prototype['faction'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} attributes
 */
DungeonsandtrollsMonster.prototype['attributes'] = undefined;

/**
 * @member {Array.<module:model/DungeonsandtrollsItem>} equippedItems
 */
DungeonsandtrollsMonster.prototype['equippedItems'] = undefined;

/**
 * @member {Number} score
 */
DungeonsandtrollsMonster.prototype['score'] = undefined;

/**
 * @member {String} algorithm
 */
DungeonsandtrollsMonster.prototype['algorithm'] = undefined;

/**
 * @member {Array.<module:model/DungeonsandtrollsDroppable>} onDeath
 */
DungeonsandtrollsMonster.prototype['onDeath'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} maxAttributes
 */
DungeonsandtrollsMonster.prototype['maxAttributes'] = undefined;

/**
 * @member {Number} lastDamageTaken
 */
DungeonsandtrollsMonster.prototype['lastDamageTaken'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsStun} stun
 */
DungeonsandtrollsMonster.prototype['stun'] = undefined;






export default DungeonsandtrollsMonster;

