/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DungeonsandtrollsDamageType.
* @enum {}
* @readonly
*/
export default class DungeonsandtrollsDamageType {
    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "slash"
         * @const
         */
        "slash" = "slash";

    
        /**
         * value: "pierce"
         * @const
         */
        "pierce" = "pierce";

    
        /**
         * value: "fire"
         * @const
         */
        "fire" = "fire";

    
        /**
         * value: "poison"
         * @const
         */
        "poison" = "poison";

    
        /**
         * value: "electric"
         * @const
         */
        "electric" = "electric";

    

    /**
    * Returns a <code>DungeonsandtrollsDamageType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DungeonsandtrollsDamageType} The enum <code>DungeonsandtrollsDamageType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

