/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsItemType from './DungeonsandtrollsItemType';

/**
 * The DungeonsandtrollsSimpleItem model module.
 * @module model/DungeonsandtrollsSimpleItem
 * @version 1.7.0
 */
class DungeonsandtrollsSimpleItem {
    /**
     * Constructs a new <code>DungeonsandtrollsSimpleItem</code>.
     * @alias module:model/DungeonsandtrollsSimpleItem
     */
    constructor() { 
        
        DungeonsandtrollsSimpleItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsSimpleItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsSimpleItem} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsSimpleItem} The populated <code>DungeonsandtrollsSimpleItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsSimpleItem();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('slot')) {
                obj['slot'] = DungeonsandtrollsItemType.constructFromObject(data['slot']);
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
DungeonsandtrollsSimpleItem.prototype['name'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsItemType} slot
 */
DungeonsandtrollsSimpleItem.prototype['slot'] = undefined;

/**
 * @member {String} icon
 */
DungeonsandtrollsSimpleItem.prototype['icon'] = undefined;






export default DungeonsandtrollsSimpleItem;

