/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DungeonsandtrollsItemType.
* @enum {}
* @readonly
*/
export default class DungeonsandtrollsItemType {
    
        /**
         * value: "head"
         * @const
         */
        "head" = "head";

    
        /**
         * value: "mainHand"
         * @const
         */
        "mainHand" = "mainHand";

    
        /**
         * value: "offHand"
         * @const
         */
        "offHand" = "offHand";

    
        /**
         * value: "body"
         * @const
         */
        "body" = "body";

    
        /**
         * value: "legs"
         * @const
         */
        "legs" = "legs";

    
        /**
         * value: "neck"
         * @const
         */
        "neck" = "neck";

    

    /**
    * Returns a <code>DungeonsandtrollsItemType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DungeonsandtrollsItemType} The enum <code>DungeonsandtrollsItemType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

