/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsDecoration model module.
 * @module model/DungeonsandtrollsDecoration
 * @version 1.7.0
 */
class DungeonsandtrollsDecoration {
    /**
     * Constructs a new <code>DungeonsandtrollsDecoration</code>.
     * @alias module:model/DungeonsandtrollsDecoration
     */
    constructor() { 
        
        DungeonsandtrollsDecoration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsDecoration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsDecoration} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsDecoration} The populated <code>DungeonsandtrollsDecoration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsDecoration();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
DungeonsandtrollsDecoration.prototype['name'] = undefined;

/**
 * @member {String} type
 */
DungeonsandtrollsDecoration.prototype['type'] = undefined;

/**
 * @member {String} icon
 */
DungeonsandtrollsDecoration.prototype['icon'] = undefined;






export default DungeonsandtrollsDecoration;

