/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsMapObjects from './DungeonsandtrollsMapObjects';

/**
 * The DungeonsandtrollsLevel model module.
 * @module model/DungeonsandtrollsLevel
 * @version 1.7.0
 */
class DungeonsandtrollsLevel {
    /**
     * Constructs a new <code>DungeonsandtrollsLevel</code>.
     * @alias module:model/DungeonsandtrollsLevel
     */
    constructor() { 
        
        DungeonsandtrollsLevel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsLevel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsLevel} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsLevel} The populated <code>DungeonsandtrollsLevel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsLevel();

            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('horror')) {
                obj['horror'] = ApiClient.convertToType(data['horror'], 'Number');
            }
            if (data.hasOwnProperty('free')) {
                obj['free'] = ApiClient.convertToType(data['free'], [[Object]]);
            }
            if (data.hasOwnProperty('objects')) {
                obj['objects'] = ApiClient.convertToType(data['objects'], [DungeonsandtrollsMapObjects]);
            }
            if (data.hasOwnProperty('ascii')) {
                obj['ascii'] = ApiClient.convertToType(data['ascii'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} level
 */
DungeonsandtrollsLevel.prototype['level'] = undefined;

/**
 * @member {Number} width
 */
DungeonsandtrollsLevel.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
DungeonsandtrollsLevel.prototype['height'] = undefined;

/**
 * @member {Number} horror
 */
DungeonsandtrollsLevel.prototype['horror'] = undefined;

/**
 * @member {Array.<Array.<Object>>} free
 */
DungeonsandtrollsLevel.prototype['free'] = undefined;

/**
 * @member {Array.<module:model/DungeonsandtrollsMapObjects>} objects
 */
DungeonsandtrollsLevel.prototype['objects'] = undefined;

/**
 * @member {Array.<String>} ascii
 */
DungeonsandtrollsLevel.prototype['ascii'] = undefined;






export default DungeonsandtrollsLevel;

