/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsCharacter from './DungeonsandtrollsCharacter';

/**
 * The DungeonsandtrollsPlayersInfo model module.
 * @module model/DungeonsandtrollsPlayersInfo
 * @version 1.7.0
 */
class DungeonsandtrollsPlayersInfo {
    /**
     * Constructs a new <code>DungeonsandtrollsPlayersInfo</code>.
     * @alias module:model/DungeonsandtrollsPlayersInfo
     */
    constructor() { 
        
        DungeonsandtrollsPlayersInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsPlayersInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsPlayersInfo} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsPlayersInfo} The populated <code>DungeonsandtrollsPlayersInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsPlayersInfo();

            if (data.hasOwnProperty('players')) {
                obj['players'] = ApiClient.convertToType(data['players'], [DungeonsandtrollsCharacter]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/DungeonsandtrollsCharacter>} players
 */
DungeonsandtrollsPlayersInfo.prototype['players'] = undefined;






export default DungeonsandtrollsPlayersInfo;

