/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsCommandsBatch from './DungeonsandtrollsCommandsBatch';

/**
 * The DungeonsandtrollsCommandsForMonsters model module.
 * @module model/DungeonsandtrollsCommandsForMonsters
 * @version 1.7.0
 */
class DungeonsandtrollsCommandsForMonsters {
    /**
     * Constructs a new <code>DungeonsandtrollsCommandsForMonsters</code>.
     * @alias module:model/DungeonsandtrollsCommandsForMonsters
     */
    constructor() { 
        
        DungeonsandtrollsCommandsForMonsters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsCommandsForMonsters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsCommandsForMonsters} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsCommandsForMonsters} The populated <code>DungeonsandtrollsCommandsForMonsters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsCommandsForMonsters();

            if (data.hasOwnProperty('commands')) {
                obj['commands'] = ApiClient.convertToType(data['commands'], {'String': DungeonsandtrollsCommandsBatch});
            }
        }
        return obj;
    }


}

/**
 * Monster ID with corresponding batch of commands.
 * @member {Object.<String, module:model/DungeonsandtrollsCommandsBatch>} commands
 */
DungeonsandtrollsCommandsForMonsters.prototype['commands'] = undefined;






export default DungeonsandtrollsCommandsForMonsters;

