/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsSkillGenericFlags model module.
 * @module model/DungeonsandtrollsSkillGenericFlags
 * @version 1.7.0
 */
class DungeonsandtrollsSkillGenericFlags {
    /**
     * Constructs a new <code>DungeonsandtrollsSkillGenericFlags</code>.
     * @alias module:model/DungeonsandtrollsSkillGenericFlags
     */
    constructor() { 
        
        DungeonsandtrollsSkillGenericFlags.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsSkillGenericFlags</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsSkillGenericFlags} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsSkillGenericFlags} The populated <code>DungeonsandtrollsSkillGenericFlags</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsSkillGenericFlags();

            if (data.hasOwnProperty('requiresOutOfCombat')) {
                obj['requiresOutOfCombat'] = ApiClient.convertToType(data['requiresOutOfCombat'], 'Boolean');
            }
            if (data.hasOwnProperty('requiresLineOfSight')) {
                obj['requiresLineOfSight'] = ApiClient.convertToType(data['requiresLineOfSight'], 'Boolean');
            }
            if (data.hasOwnProperty('passive')) {
                obj['passive'] = ApiClient.convertToType(data['passive'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} requiresOutOfCombat
 */
DungeonsandtrollsSkillGenericFlags.prototype['requiresOutOfCombat'] = undefined;

/**
 * @member {Boolean} requiresLineOfSight
 */
DungeonsandtrollsSkillGenericFlags.prototype['requiresLineOfSight'] = undefined;

/**
 * @member {Boolean} passive
 */
DungeonsandtrollsSkillGenericFlags.prototype['passive'] = undefined;






export default DungeonsandtrollsSkillGenericFlags;

