/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsAvailableLevels model module.
 * @module model/DungeonsandtrollsAvailableLevels
 * @version 1.7.0
 */
class DungeonsandtrollsAvailableLevels {
    /**
     * Constructs a new <code>DungeonsandtrollsAvailableLevels</code>.
     * @alias module:model/DungeonsandtrollsAvailableLevels
     */
    constructor() { 
        
        DungeonsandtrollsAvailableLevels.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsAvailableLevels</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsAvailableLevels} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsAvailableLevels} The populated <code>DungeonsandtrollsAvailableLevels</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsAvailableLevels();

            if (data.hasOwnProperty('levels')) {
                obj['levels'] = ApiClient.convertToType(data['levels'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} levels
 */
DungeonsandtrollsAvailableLevels.prototype['levels'] = undefined;






export default DungeonsandtrollsAvailableLevels;

