/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsDroppable from './DungeonsandtrollsDroppable';
import DungeonsandtrollsSkillAttributes from './DungeonsandtrollsSkillAttributes';
import DungeonsandtrollsSkillSpecificFlags from './DungeonsandtrollsSkillSpecificFlags';

/**
 * The DungeonsandtrollsSkillEffect model module.
 * @module model/DungeonsandtrollsSkillEffect
 * @version 1.7.0
 */
class DungeonsandtrollsSkillEffect {
    /**
     * Constructs a new <code>DungeonsandtrollsSkillEffect</code>.
     * @alias module:model/DungeonsandtrollsSkillEffect
     */
    constructor() { 
        
        DungeonsandtrollsSkillEffect.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsSkillEffect</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsSkillEffect} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsSkillEffect} The populated <code>DungeonsandtrollsSkillEffect</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsSkillEffect();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = DungeonsandtrollsSkillAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('flags')) {
                obj['flags'] = DungeonsandtrollsSkillSpecificFlags.constructFromObject(data['flags']);
            }
            if (data.hasOwnProperty('summons')) {
                obj['summons'] = ApiClient.convertToType(data['summons'], [DungeonsandtrollsDroppable]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DungeonsandtrollsSkillAttributes} attributes
 */
DungeonsandtrollsSkillEffect.prototype['attributes'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsSkillSpecificFlags} flags
 */
DungeonsandtrollsSkillEffect.prototype['flags'] = undefined;

/**
 * @member {Array.<module:model/DungeonsandtrollsDroppable>} summons
 */
DungeonsandtrollsSkillEffect.prototype['summons'] = undefined;






export default DungeonsandtrollsSkillEffect;

