/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsPosition model module.
 * @module model/DungeonsandtrollsPosition
 * @version 1.7.0
 */
class DungeonsandtrollsPosition {
    /**
     * Constructs a new <code>DungeonsandtrollsPosition</code>.
     * @alias module:model/DungeonsandtrollsPosition
     */
    constructor() { 
        
        DungeonsandtrollsPosition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsPosition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsPosition} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsPosition} The populated <code>DungeonsandtrollsPosition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsPosition();

            if (data.hasOwnProperty('positionX')) {
                obj['positionX'] = ApiClient.convertToType(data['positionX'], 'Number');
            }
            if (data.hasOwnProperty('positionY')) {
                obj['positionY'] = ApiClient.convertToType(data['positionY'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} positionX
 */
DungeonsandtrollsPosition.prototype['positionX'] = undefined;

/**
 * @member {Number} positionY
 */
DungeonsandtrollsPosition.prototype['positionY'] = undefined;






export default DungeonsandtrollsPosition;

