/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DungeonsandtrollsEventType.
* @enum {}
* @readonly
*/
export default class DungeonsandtrollsEventType {
    
        /**
         * value: "DAMAGE"
         * @const
         */
        "DAMAGE" = "DAMAGE";

    
        /**
         * value: "MESSAGE"
         * @const
         */
        "MESSAGE" = "MESSAGE";

    
        /**
         * value: "BUY"
         * @const
         */
        "BUY" = "BUY";

    
        /**
         * value: "EQUIP"
         * @const
         */
        "EQUIP" = "EQUIP";

    
        /**
         * value: "ERROR"
         * @const
         */
        "ERROR" = "ERROR";

    
        /**
         * value: "SKILL"
         * @const
         */
        "SKILL" = "SKILL";

    
        /**
         * value: "DEATH"
         * @const
         */
        "DEATH" = "DEATH";

    
        /**
         * value: "SCORE"
         * @const
         */
        "SCORE" = "SCORE";

    
        /**
         * value: "MOVE"
         * @const
         */
        "MOVE" = "MOVE";

    
        /**
         * value: "AOE"
         * @const
         */
        "AOE" = "AOE";

    

    /**
    * Returns a <code>DungeonsandtrollsEventType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DungeonsandtrollsEventType} The enum <code>DungeonsandtrollsEventType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

