/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsPosition from './DungeonsandtrollsPosition';

/**
 * The DungeonsandtrollsSkillUse model module.
 * @module model/DungeonsandtrollsSkillUse
 * @version 1.7.0
 */
class DungeonsandtrollsSkillUse {
    /**
     * Constructs a new <code>DungeonsandtrollsSkillUse</code>.
     * @alias module:model/DungeonsandtrollsSkillUse
     */
    constructor() { 
        
        DungeonsandtrollsSkillUse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsSkillUse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsSkillUse} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsSkillUse} The populated <code>DungeonsandtrollsSkillUse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsSkillUse();

            if (data.hasOwnProperty('skillId')) {
                obj['skillId'] = ApiClient.convertToType(data['skillId'], 'String');
            }
            if (data.hasOwnProperty('targetId')) {
                obj['targetId'] = ApiClient.convertToType(data['targetId'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = DungeonsandtrollsPosition.constructFromObject(data['position']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} skillId
 */
DungeonsandtrollsSkillUse.prototype['skillId'] = undefined;

/**
 * @member {String} targetId
 */
DungeonsandtrollsSkillUse.prototype['targetId'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsPosition} position
 */
DungeonsandtrollsSkillUse.prototype['position'] = undefined;






export default DungeonsandtrollsSkillUse;

