/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsSkillSpecificFlags model module.
 * @module model/DungeonsandtrollsSkillSpecificFlags
 * @version 1.7.0
 */
class DungeonsandtrollsSkillSpecificFlags {
    /**
     * Constructs a new <code>DungeonsandtrollsSkillSpecificFlags</code>.
     * @alias module:model/DungeonsandtrollsSkillSpecificFlags
     */
    constructor() { 
        
        DungeonsandtrollsSkillSpecificFlags.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsSkillSpecificFlags</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsSkillSpecificFlags} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsSkillSpecificFlags} The populated <code>DungeonsandtrollsSkillSpecificFlags</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsSkillSpecificFlags();

            if (data.hasOwnProperty('movement')) {
                obj['movement'] = ApiClient.convertToType(data['movement'], 'Boolean');
            }
            if (data.hasOwnProperty('knockback')) {
                obj['knockback'] = ApiClient.convertToType(data['knockback'], 'Boolean');
            }
            if (data.hasOwnProperty('stun')) {
                obj['stun'] = ApiClient.convertToType(data['stun'], 'Boolean');
            }
            if (data.hasOwnProperty('groundEffect')) {
                obj['groundEffect'] = ApiClient.convertToType(data['groundEffect'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} movement
 */
DungeonsandtrollsSkillSpecificFlags.prototype['movement'] = undefined;

/**
 * @member {Boolean} knockback
 */
DungeonsandtrollsSkillSpecificFlags.prototype['knockback'] = undefined;

/**
 * @member {Boolean} stun
 */
DungeonsandtrollsSkillSpecificFlags.prototype['stun'] = undefined;

/**
 * @member {Boolean} groundEffect
 */
DungeonsandtrollsSkillSpecificFlags.prototype['groundEffect'] = undefined;






export default DungeonsandtrollsSkillSpecificFlags;

