/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsStun model module.
 * @module model/DungeonsandtrollsStun
 * @version 1.7.0
 */
class DungeonsandtrollsStun {
    /**
     * Constructs a new <code>DungeonsandtrollsStun</code>.
     * @alias module:model/DungeonsandtrollsStun
     */
    constructor() { 
        
        DungeonsandtrollsStun.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsStun</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsStun} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsStun} The populated <code>DungeonsandtrollsStun</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsStun();

            if (data.hasOwnProperty('isStunned')) {
                obj['isStunned'] = ApiClient.convertToType(data['isStunned'], 'Boolean');
            }
            if (data.hasOwnProperty('isImmune')) {
                obj['isImmune'] = ApiClient.convertToType(data['isImmune'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isStunned
 */
DungeonsandtrollsStun.prototype['isStunned'] = undefined;

/**
 * @member {Boolean} isImmune
 */
DungeonsandtrollsStun.prototype['isImmune'] = undefined;






export default DungeonsandtrollsStun;

