/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsPosition from './DungeonsandtrollsPosition';

/**
 * The DungeonsandtrollsKey model module.
 * @module model/DungeonsandtrollsKey
 * @version 1.7.0
 */
class DungeonsandtrollsKey {
    /**
     * Constructs a new <code>DungeonsandtrollsKey</code>.
     * @alias module:model/DungeonsandtrollsKey
     */
    constructor() { 
        
        DungeonsandtrollsKey.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsKey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsKey} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsKey} The populated <code>DungeonsandtrollsKey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsKey();

            if (data.hasOwnProperty('doors')) {
                obj['doors'] = ApiClient.convertToType(data['doors'], [DungeonsandtrollsPosition]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/DungeonsandtrollsPosition>} doors
 */
DungeonsandtrollsKey.prototype['doors'] = undefined;






export default DungeonsandtrollsKey;

