/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsAttributes from './DungeonsandtrollsAttributes';
import DungeonsandtrollsItemType from './DungeonsandtrollsItemType';
import DungeonsandtrollsSkill from './DungeonsandtrollsSkill';

/**
 * The DungeonsandtrollsItem model module.
 * @module model/DungeonsandtrollsItem
 * @version 1.7.0
 */
class DungeonsandtrollsItem {
    /**
     * Constructs a new <code>DungeonsandtrollsItem</code>.
     * @alias module:model/DungeonsandtrollsItem
     */
    constructor() { 
        
        DungeonsandtrollsItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsItem} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsItem} The populated <code>DungeonsandtrollsItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('slot')) {
                obj['slot'] = DungeonsandtrollsItemType.constructFromObject(data['slot']);
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = DungeonsandtrollsAttributes.constructFromObject(data['requirements']);
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = DungeonsandtrollsAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('skills')) {
                obj['skills'] = ApiClient.convertToType(data['skills'], [DungeonsandtrollsSkill]);
            }
            if (data.hasOwnProperty('icon')) {
                obj['icon'] = ApiClient.convertToType(data['icon'], 'String');
            }
            if (data.hasOwnProperty('unidentified')) {
                obj['unidentified'] = ApiClient.convertToType(data['unidentified'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
DungeonsandtrollsItem.prototype['id'] = undefined;

/**
 * @member {String} name
 */
DungeonsandtrollsItem.prototype['name'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsItemType} slot
 */
DungeonsandtrollsItem.prototype['slot'] = undefined;

/**
 * @member {Number} price
 */
DungeonsandtrollsItem.prototype['price'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} requirements
 */
DungeonsandtrollsItem.prototype['requirements'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} attributes
 */
DungeonsandtrollsItem.prototype['attributes'] = undefined;

/**
 * @member {Array.<module:model/DungeonsandtrollsSkill>} skills
 */
DungeonsandtrollsItem.prototype['skills'] = undefined;

/**
 * @member {String} icon
 */
DungeonsandtrollsItem.prototype['icon'] = undefined;

/**
 * @member {Boolean} unidentified
 */
DungeonsandtrollsItem.prototype['unidentified'] = undefined;






export default DungeonsandtrollsItem;

