/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsCoordinates model module.
 * @module model/DungeonsandtrollsCoordinates
 * @version 1.7.0
 */
class DungeonsandtrollsCoordinates {
    /**
     * Constructs a new <code>DungeonsandtrollsCoordinates</code>.
     * @alias module:model/DungeonsandtrollsCoordinates
     */
    constructor() { 
        
        DungeonsandtrollsCoordinates.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsCoordinates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsCoordinates} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsCoordinates} The populated <code>DungeonsandtrollsCoordinates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsCoordinates();

            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('positionX')) {
                obj['positionX'] = ApiClient.convertToType(data['positionX'], 'Number');
            }
            if (data.hasOwnProperty('positionY')) {
                obj['positionY'] = ApiClient.convertToType(data['positionY'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} level
 */
DungeonsandtrollsCoordinates.prototype['level'] = undefined;

/**
 * @member {Number} positionX
 */
DungeonsandtrollsCoordinates.prototype['positionX'] = undefined;

/**
 * @member {Number} positionY
 */
DungeonsandtrollsCoordinates.prototype['positionY'] = undefined;






export default DungeonsandtrollsCoordinates;

