/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DungeonsandtrollsAttributes from './DungeonsandtrollsAttributes';

/**
 * The DungeonsandtrollsSkillAttributes model module.
 * @module model/DungeonsandtrollsSkillAttributes
 * @version 1.7.0
 */
class DungeonsandtrollsSkillAttributes {
    /**
     * Constructs a new <code>DungeonsandtrollsSkillAttributes</code>.
     * @alias module:model/DungeonsandtrollsSkillAttributes
     */
    constructor() { 
        
        DungeonsandtrollsSkillAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsSkillAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsSkillAttributes} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsSkillAttributes} The populated <code>DungeonsandtrollsSkillAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsSkillAttributes();

            if (data.hasOwnProperty('strength')) {
                obj['strength'] = DungeonsandtrollsAttributes.constructFromObject(data['strength']);
            }
            if (data.hasOwnProperty('dexterity')) {
                obj['dexterity'] = DungeonsandtrollsAttributes.constructFromObject(data['dexterity']);
            }
            if (data.hasOwnProperty('intelligence')) {
                obj['intelligence'] = DungeonsandtrollsAttributes.constructFromObject(data['intelligence']);
            }
            if (data.hasOwnProperty('willpower')) {
                obj['willpower'] = DungeonsandtrollsAttributes.constructFromObject(data['willpower']);
            }
            if (data.hasOwnProperty('constitution')) {
                obj['constitution'] = DungeonsandtrollsAttributes.constructFromObject(data['constitution']);
            }
            if (data.hasOwnProperty('slashResist')) {
                obj['slashResist'] = DungeonsandtrollsAttributes.constructFromObject(data['slashResist']);
            }
            if (data.hasOwnProperty('pierceResist')) {
                obj['pierceResist'] = DungeonsandtrollsAttributes.constructFromObject(data['pierceResist']);
            }
            if (data.hasOwnProperty('fireResist')) {
                obj['fireResist'] = DungeonsandtrollsAttributes.constructFromObject(data['fireResist']);
            }
            if (data.hasOwnProperty('poisonResist')) {
                obj['poisonResist'] = DungeonsandtrollsAttributes.constructFromObject(data['poisonResist']);
            }
            if (data.hasOwnProperty('electricResist')) {
                obj['electricResist'] = DungeonsandtrollsAttributes.constructFromObject(data['electricResist']);
            }
            if (data.hasOwnProperty('life')) {
                obj['life'] = DungeonsandtrollsAttributes.constructFromObject(data['life']);
            }
            if (data.hasOwnProperty('stamina')) {
                obj['stamina'] = DungeonsandtrollsAttributes.constructFromObject(data['stamina']);
            }
            if (data.hasOwnProperty('mana')) {
                obj['mana'] = DungeonsandtrollsAttributes.constructFromObject(data['mana']);
            }
            if (data.hasOwnProperty('constant')) {
                obj['constant'] = DungeonsandtrollsAttributes.constructFromObject(data['constant']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DungeonsandtrollsAttributes} strength
 */
DungeonsandtrollsSkillAttributes.prototype['strength'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} dexterity
 */
DungeonsandtrollsSkillAttributes.prototype['dexterity'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} intelligence
 */
DungeonsandtrollsSkillAttributes.prototype['intelligence'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} willpower
 */
DungeonsandtrollsSkillAttributes.prototype['willpower'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} constitution
 */
DungeonsandtrollsSkillAttributes.prototype['constitution'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} slashResist
 */
DungeonsandtrollsSkillAttributes.prototype['slashResist'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} pierceResist
 */
DungeonsandtrollsSkillAttributes.prototype['pierceResist'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} fireResist
 */
DungeonsandtrollsSkillAttributes.prototype['fireResist'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} poisonResist
 */
DungeonsandtrollsSkillAttributes.prototype['poisonResist'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} electricResist
 */
DungeonsandtrollsSkillAttributes.prototype['electricResist'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} life
 */
DungeonsandtrollsSkillAttributes.prototype['life'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} stamina
 */
DungeonsandtrollsSkillAttributes.prototype['stamina'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} mana
 */
DungeonsandtrollsSkillAttributes.prototype['mana'] = undefined;

/**
 * @member {module:model/DungeonsandtrollsAttributes} constant
 */
DungeonsandtrollsSkillAttributes.prototype['constant'] = undefined;






export default DungeonsandtrollsSkillAttributes;

