/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsIdentifiers model module.
 * @module model/DungeonsandtrollsIdentifiers
 * @version 1.7.0
 */
class DungeonsandtrollsIdentifiers {
    /**
     * Constructs a new <code>DungeonsandtrollsIdentifiers</code>.
     * @alias module:model/DungeonsandtrollsIdentifiers
     */
    constructor() { 
        
        DungeonsandtrollsIdentifiers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsIdentifiers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsIdentifiers} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsIdentifiers} The populated <code>DungeonsandtrollsIdentifiers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsIdentifiers();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} ids
 */
DungeonsandtrollsIdentifiers.prototype['ids'] = undefined;






export default DungeonsandtrollsIdentifiers;

