/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DungeonsandtrollsMessage model module.
 * @module model/DungeonsandtrollsMessage
 * @version 1.7.0
 */
class DungeonsandtrollsMessage {
    /**
     * Constructs a new <code>DungeonsandtrollsMessage</code>.
     * @alias module:model/DungeonsandtrollsMessage
     */
    constructor() { 
        
        DungeonsandtrollsMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DungeonsandtrollsMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DungeonsandtrollsMessage} obj Optional instance to populate.
     * @return {module:model/DungeonsandtrollsMessage} The populated <code>DungeonsandtrollsMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DungeonsandtrollsMessage();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} text
 */
DungeonsandtrollsMessage.prototype['text'] = undefined;






export default DungeonsandtrollsMessage;

