/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DungeonsandtrollsAttributes from './model/DungeonsandtrollsAttributes';
import DungeonsandtrollsAvailableLevels from './model/DungeonsandtrollsAvailableLevels';
import DungeonsandtrollsCharacter from './model/DungeonsandtrollsCharacter';
import DungeonsandtrollsCommandsBatch from './model/DungeonsandtrollsCommandsBatch';
import DungeonsandtrollsCommandsForMonsters from './model/DungeonsandtrollsCommandsForMonsters';
import DungeonsandtrollsCoordinates from './model/DungeonsandtrollsCoordinates';
import DungeonsandtrollsDamageType from './model/DungeonsandtrollsDamageType';
import DungeonsandtrollsDecoration from './model/DungeonsandtrollsDecoration';
import DungeonsandtrollsDroppable from './model/DungeonsandtrollsDroppable';
import DungeonsandtrollsEffect from './model/DungeonsandtrollsEffect';
import DungeonsandtrollsEvent from './model/DungeonsandtrollsEvent';
import DungeonsandtrollsEventType from './model/DungeonsandtrollsEventType';
import DungeonsandtrollsGameState from './model/DungeonsandtrollsGameState';
import DungeonsandtrollsIdentifier from './model/DungeonsandtrollsIdentifier';
import DungeonsandtrollsIdentifiers from './model/DungeonsandtrollsIdentifiers';
import DungeonsandtrollsItem from './model/DungeonsandtrollsItem';
import DungeonsandtrollsItemType from './model/DungeonsandtrollsItemType';
import DungeonsandtrollsKey from './model/DungeonsandtrollsKey';
import DungeonsandtrollsLevel from './model/DungeonsandtrollsLevel';
import DungeonsandtrollsMap from './model/DungeonsandtrollsMap';
import DungeonsandtrollsMapObjects from './model/DungeonsandtrollsMapObjects';
import DungeonsandtrollsMessage from './model/DungeonsandtrollsMessage';
import DungeonsandtrollsMonster from './model/DungeonsandtrollsMonster';
import DungeonsandtrollsPlayersInfo from './model/DungeonsandtrollsPlayersInfo';
import DungeonsandtrollsPosition from './model/DungeonsandtrollsPosition';
import DungeonsandtrollsRegistration from './model/DungeonsandtrollsRegistration';
import DungeonsandtrollsSimpleItem from './model/DungeonsandtrollsSimpleItem';
import DungeonsandtrollsSkill from './model/DungeonsandtrollsSkill';
import DungeonsandtrollsSkillAttributes from './model/DungeonsandtrollsSkillAttributes';
import DungeonsandtrollsSkillEffect from './model/DungeonsandtrollsSkillEffect';
import DungeonsandtrollsSkillGenericFlags from './model/DungeonsandtrollsSkillGenericFlags';
import DungeonsandtrollsSkillSpecificFlags from './model/DungeonsandtrollsSkillSpecificFlags';
import DungeonsandtrollsSkillUse from './model/DungeonsandtrollsSkillUse';
import DungeonsandtrollsStun from './model/DungeonsandtrollsStun';
import DungeonsandtrollsUser from './model/DungeonsandtrollsUser';
import DungeonsandtrollsWaypoint from './model/DungeonsandtrollsWaypoint';
import ProtobufAny from './model/ProtobufAny';
import ProtobufNullValue from './model/ProtobufNullValue';
import RpcStatus from './model/RpcStatus';
import SkillTarget from './model/SkillTarget';
import DungeonsAndTrollsApi from './api/DungeonsAndTrollsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DungeonsAndTrolls = require('index'); // See note below*.
* var xxxSvc = new DungeonsAndTrolls.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DungeonsAndTrolls.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DungeonsAndTrolls.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DungeonsAndTrolls.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.7.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DungeonsandtrollsAttributes model constructor.
     * @property {module:model/DungeonsandtrollsAttributes}
     */
    DungeonsandtrollsAttributes,

    /**
     * The DungeonsandtrollsAvailableLevels model constructor.
     * @property {module:model/DungeonsandtrollsAvailableLevels}
     */
    DungeonsandtrollsAvailableLevels,

    /**
     * The DungeonsandtrollsCharacter model constructor.
     * @property {module:model/DungeonsandtrollsCharacter}
     */
    DungeonsandtrollsCharacter,

    /**
     * The DungeonsandtrollsCommandsBatch model constructor.
     * @property {module:model/DungeonsandtrollsCommandsBatch}
     */
    DungeonsandtrollsCommandsBatch,

    /**
     * The DungeonsandtrollsCommandsForMonsters model constructor.
     * @property {module:model/DungeonsandtrollsCommandsForMonsters}
     */
    DungeonsandtrollsCommandsForMonsters,

    /**
     * The DungeonsandtrollsCoordinates model constructor.
     * @property {module:model/DungeonsandtrollsCoordinates}
     */
    DungeonsandtrollsCoordinates,

    /**
     * The DungeonsandtrollsDamageType model constructor.
     * @property {module:model/DungeonsandtrollsDamageType}
     */
    DungeonsandtrollsDamageType,

    /**
     * The DungeonsandtrollsDecoration model constructor.
     * @property {module:model/DungeonsandtrollsDecoration}
     */
    DungeonsandtrollsDecoration,

    /**
     * The DungeonsandtrollsDroppable model constructor.
     * @property {module:model/DungeonsandtrollsDroppable}
     */
    DungeonsandtrollsDroppable,

    /**
     * The DungeonsandtrollsEffect model constructor.
     * @property {module:model/DungeonsandtrollsEffect}
     */
    DungeonsandtrollsEffect,

    /**
     * The DungeonsandtrollsEvent model constructor.
     * @property {module:model/DungeonsandtrollsEvent}
     */
    DungeonsandtrollsEvent,

    /**
     * The DungeonsandtrollsEventType model constructor.
     * @property {module:model/DungeonsandtrollsEventType}
     */
    DungeonsandtrollsEventType,

    /**
     * The DungeonsandtrollsGameState model constructor.
     * @property {module:model/DungeonsandtrollsGameState}
     */
    DungeonsandtrollsGameState,

    /**
     * The DungeonsandtrollsIdentifier model constructor.
     * @property {module:model/DungeonsandtrollsIdentifier}
     */
    DungeonsandtrollsIdentifier,

    /**
     * The DungeonsandtrollsIdentifiers model constructor.
     * @property {module:model/DungeonsandtrollsIdentifiers}
     */
    DungeonsandtrollsIdentifiers,

    /**
     * The DungeonsandtrollsItem model constructor.
     * @property {module:model/DungeonsandtrollsItem}
     */
    DungeonsandtrollsItem,

    /**
     * The DungeonsandtrollsItemType model constructor.
     * @property {module:model/DungeonsandtrollsItemType}
     */
    DungeonsandtrollsItemType,

    /**
     * The DungeonsandtrollsKey model constructor.
     * @property {module:model/DungeonsandtrollsKey}
     */
    DungeonsandtrollsKey,

    /**
     * The DungeonsandtrollsLevel model constructor.
     * @property {module:model/DungeonsandtrollsLevel}
     */
    DungeonsandtrollsLevel,

    /**
     * The DungeonsandtrollsMap model constructor.
     * @property {module:model/DungeonsandtrollsMap}
     */
    DungeonsandtrollsMap,

    /**
     * The DungeonsandtrollsMapObjects model constructor.
     * @property {module:model/DungeonsandtrollsMapObjects}
     */
    DungeonsandtrollsMapObjects,

    /**
     * The DungeonsandtrollsMessage model constructor.
     * @property {module:model/DungeonsandtrollsMessage}
     */
    DungeonsandtrollsMessage,

    /**
     * The DungeonsandtrollsMonster model constructor.
     * @property {module:model/DungeonsandtrollsMonster}
     */
    DungeonsandtrollsMonster,

    /**
     * The DungeonsandtrollsPlayersInfo model constructor.
     * @property {module:model/DungeonsandtrollsPlayersInfo}
     */
    DungeonsandtrollsPlayersInfo,

    /**
     * The DungeonsandtrollsPosition model constructor.
     * @property {module:model/DungeonsandtrollsPosition}
     */
    DungeonsandtrollsPosition,

    /**
     * The DungeonsandtrollsRegistration model constructor.
     * @property {module:model/DungeonsandtrollsRegistration}
     */
    DungeonsandtrollsRegistration,

    /**
     * The DungeonsandtrollsSimpleItem model constructor.
     * @property {module:model/DungeonsandtrollsSimpleItem}
     */
    DungeonsandtrollsSimpleItem,

    /**
     * The DungeonsandtrollsSkill model constructor.
     * @property {module:model/DungeonsandtrollsSkill}
     */
    DungeonsandtrollsSkill,

    /**
     * The DungeonsandtrollsSkillAttributes model constructor.
     * @property {module:model/DungeonsandtrollsSkillAttributes}
     */
    DungeonsandtrollsSkillAttributes,

    /**
     * The DungeonsandtrollsSkillEffect model constructor.
     * @property {module:model/DungeonsandtrollsSkillEffect}
     */
    DungeonsandtrollsSkillEffect,

    /**
     * The DungeonsandtrollsSkillGenericFlags model constructor.
     * @property {module:model/DungeonsandtrollsSkillGenericFlags}
     */
    DungeonsandtrollsSkillGenericFlags,

    /**
     * The DungeonsandtrollsSkillSpecificFlags model constructor.
     * @property {module:model/DungeonsandtrollsSkillSpecificFlags}
     */
    DungeonsandtrollsSkillSpecificFlags,

    /**
     * The DungeonsandtrollsSkillUse model constructor.
     * @property {module:model/DungeonsandtrollsSkillUse}
     */
    DungeonsandtrollsSkillUse,

    /**
     * The DungeonsandtrollsStun model constructor.
     * @property {module:model/DungeonsandtrollsStun}
     */
    DungeonsandtrollsStun,

    /**
     * The DungeonsandtrollsUser model constructor.
     * @property {module:model/DungeonsandtrollsUser}
     */
    DungeonsandtrollsUser,

    /**
     * The DungeonsandtrollsWaypoint model constructor.
     * @property {module:model/DungeonsandtrollsWaypoint}
     */
    DungeonsandtrollsWaypoint,

    /**
     * The ProtobufAny model constructor.
     * @property {module:model/ProtobufAny}
     */
    ProtobufAny,

    /**
     * The ProtobufNullValue model constructor.
     * @property {module:model/ProtobufNullValue}
     */
    ProtobufNullValue,

    /**
     * The RpcStatus model constructor.
     * @property {module:model/RpcStatus}
     */
    RpcStatus,

    /**
     * The SkillTarget model constructor.
     * @property {module:model/SkillTarget}
     */
    SkillTarget,

    /**
    * The DungeonsAndTrollsApi service constructor.
    * @property {module:api/DungeonsAndTrollsApi}
    */
    DungeonsAndTrollsApi
};
