/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DungeonsAndTrolls);
  }
}(this, function(expect, DungeonsAndTrolls) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DungeonsandtrollsGameState', function() {
    it('should create an instance of DungeonsandtrollsGameState', function() {
      // uncomment below and update the code to test DungeonsandtrollsGameState
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be.a(DungeonsAndTrolls.DungeonsandtrollsGameState);
    });

    it('should have the property map (base name: "map")', function() {
      // uncomment below and update the code to test the property map
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property shopItems (base name: "shopItems")', function() {
      // uncomment below and update the code to test the property shopItems
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property character (base name: "character")', function() {
      // uncomment below and update the code to test the property character
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property currentPosition (base name: "currentPosition")', function() {
      // uncomment below and update the code to test the property currentPosition
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property currentLevel (base name: "currentLevel")', function() {
      // uncomment below and update the code to test the property currentLevel
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property tick (base name: "tick")', function() {
      // uncomment below and update the code to test the property tick
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property events (base name: "events")', function() {
      // uncomment below and update the code to test the property events
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

    it('should have the property maxLevel (base name: "maxLevel")', function() {
      // uncomment below and update the code to test the property maxLevel
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsGameState();
      //expect(instance).to.be();
    });

  });

}));
