/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DungeonsAndTrolls);
  }
}(this, function(expect, DungeonsAndTrolls) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DungeonsandtrollsSkill', function() {
    it('should create an instance of DungeonsandtrollsSkill', function() {
      // uncomment below and update the code to test DungeonsandtrollsSkill
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be.a(DungeonsAndTrolls.DungeonsandtrollsSkill);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property target (base name: "target")', function() {
      // uncomment below and update the code to test the property target
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property cost (base name: "cost")', function() {
      // uncomment below and update the code to test the property cost
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property range (base name: "range")', function() {
      // uncomment below and update the code to test the property range
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property radius (base name: "radius")', function() {
      // uncomment below and update the code to test the property radius
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property damageAmount (base name: "damageAmount")', function() {
      // uncomment below and update the code to test the property damageAmount
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property damageType (base name: "damageType")', function() {
      // uncomment below and update the code to test the property damageType
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property casterEffects (base name: "casterEffects")', function() {
      // uncomment below and update the code to test the property casterEffects
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property targetEffects (base name: "targetEffects")', function() {
      // uncomment below and update the code to test the property targetEffects
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

    it('should have the property flags (base name: "flags")', function() {
      // uncomment below and update the code to test the property flags
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkill();
      //expect(instance).to.be();
    });

  });

}));
