/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DungeonsAndTrolls);
  }
}(this, function(expect, DungeonsAndTrolls) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DungeonsandtrollsMapObjects', function() {
    it('should create an instance of DungeonsandtrollsMapObjects', function() {
      // uncomment below and update the code to test DungeonsandtrollsMapObjects
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be.a(DungeonsAndTrolls.DungeonsandtrollsMapObjects);
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property monsters (base name: "monsters")', function() {
      // uncomment below and update the code to test the property monsters
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property players (base name: "players")', function() {
      // uncomment below and update the code to test the property players
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property isStairs (base name: "isStairs")', function() {
      // uncomment below and update the code to test the property isStairs
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property portal (base name: "portal")', function() {
      // uncomment below and update the code to test the property portal
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property decorations (base name: "decorations")', function() {
      // uncomment below and update the code to test the property decorations
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property effects (base name: "effects")', function() {
      // uncomment below and update the code to test the property effects
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property isFree (base name: "isFree")', function() {
      // uncomment below and update the code to test the property isFree
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property isWall (base name: "isWall")', function() {
      // uncomment below and update the code to test the property isWall
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property isDoor (base name: "isDoor")', function() {
      // uncomment below and update the code to test the property isDoor
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

    it('should have the property isSpawn (base name: "isSpawn")', function() {
      // uncomment below and update the code to test the property isSpawn
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsMapObjects();
      //expect(instance).to.be();
    });

  });

}));
