/**
 * Dungeons and Trolls
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DungeonsAndTrolls);
  }
}(this, function(expect, DungeonsAndTrolls) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DungeonsAndTrolls.DungeonsandtrollsSkillEffect();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DungeonsandtrollsSkillEffect', function() {
    it('should create an instance of DungeonsandtrollsSkillEffect', function() {
      // uncomment below and update the code to test DungeonsandtrollsSkillEffect
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkillEffect();
      //expect(instance).to.be.a(DungeonsAndTrolls.DungeonsandtrollsSkillEffect);
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkillEffect();
      //expect(instance).to.be();
    });

    it('should have the property flags (base name: "flags")', function() {
      // uncomment below and update the code to test the property flags
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkillEffect();
      //expect(instance).to.be();
    });

    it('should have the property summons (base name: "summons")', function() {
      // uncomment below and update the code to test the property summons
      //var instance = new DungeonsAndTrolls.DungeonsandtrollsSkillEffect();
      //expect(instance).to.be();
    });

  });

}));
